apiVersion: 1

contactPoints:
  - orgId: 1
    name: Discord
    receivers:
      - uid: discord_alert
        type: discord
        settings:
          url: https://discord.com/api/webhooks/1477276961423491164/gcEFNjDjVcVIHQmq3aRbeP2sqcACmlk7m81SYDWRwxwrGGYJXBGqxOtWRYQhRxA8MRyx
